apiVersion: 1

deleteDatasources:
  - name: prometheus
    orgId: 1

datasources:
- version: 1
  name: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  editable: true
  url: http://prometheus:9090
