{
 "title": "NetworkTraffic",
 "time": { "from": "2019-07-30T07:00:30.388Z", "to": "2019-07-30T07:06:28.710Z" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod_name!=\"\", image!=\"\", container_name!=\"\"}[1m])) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"default\", pod_name!=\"\", image!=\"\", container_name!=\"\"}) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "eth0 out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{interface=\"eth0\", namespace=\"default\", pod_name=~\".*forwarder.*\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "eth0 in",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{interface=\"eth0\", namespace=\"default\", pod_name=~\".*aggregator.*\"}[1m])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}