apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vector-forwarder
  name: vector-forwarder
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-forwarder
  template:
    metadata:
      labels:
        app: vector-forwarder
    spec:
      initContainers:
      - image: watawuwu/dummy-access-log:0.2.0
        name: dummy-data
        args:
        - sh
        - -c
        - /tools/gen.bash
        volumeMounts:
        - name: data
          mountPath: /data
        - name: tools
          mountPath: /tools
      containers:
      - image: timberio/vector:0.3.0
        name: vector
        args:
        - vector
        - --config
        - /conf/vector.toml
        volumeMounts:
        - name: data
          mountPath: /data
        - name: conf
          mountPath: /conf
      volumes:
      - name: data
        emptyDir: {}
      - name: conf
        configMap:
          name: vector-forwarder
      - name: tools
        configMap:
          name: tools
          defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vector-aggregator
  name: vector-aggregator
  namespace: default
spec:
  selector:
    app: vector-aggregator
  ports:
  - name: vector
    port: 9000
    protocol: TCP
    # targetPort:: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vector-aggregator
  name: vector-aggregator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-aggregator
  template:
    metadata:
      labels:
        app: vector-aggregator
    spec:
      containers:
      - image: timberio/vector:0.3.0
        name: vector
        args:
        - vector
        - --config
        - /conf/vector.toml
        volumeMounts:
        - name: data
          mountPath: /data
        - name: conf
          mountPath: /conf
      volumes:
      - name: data
        emptyDir: {}
      - name: conf
        configMap:
          name: vector-aggregator
